BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[recommendations] ALTER COLUMN [suggestedCareers] NVARCHAR(max) NULL;
ALTER TABLE [dbo].[recommendations] ALTER COLUMN [learningPath] NVARCHAR(max) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
